# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ptj}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Grunzweig"]
  s.date = %q{2011-08-29}
  s.description = %q{An easy way to collect and analyze data about password 
  databases.}
  s.email = %q{jgrunzweig@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "etc/config.yml",
    "lib/ptj.rb",
    "lib/ptj/default_setup.rb",
    "lib/ptj/environment.rb",
    "lib/ptj/ext.rb",
    "lib/ptj/ext/datamapper_collection.rb",
    "lib/ptj/model.rb",
    "lib/ptj/model/password.rb",
    "lib/ptj/model/tag.rb",
    "lib/ptj/model/tasks.rb",
    "lib/ptj/parser.rb",
    "lib/ptj/parser/fileparser.rb",
    "lib/ptj/parser/fileparser/countpassonly.rb",
    "lib/ptj/parser/fileparser/hashpassonlycolon.rb",
    "lib/ptj/parser/fileparser/passhashonly.rb",
    "lib/ptj/parser/fileparser/passonly.rb",
    "lib/ptj/parser/fileparser/passthreecolons.rb",
    "scripts/analyze.rb",
    "scripts/generate_wordlist.rb",
    "scripts/import.rb",
    "scripts/ptj_libpath.rb",
    "spec/.helper.rb.swp",
    "spec/.test_ptj.rb.swp",
    "spec/model/password_spec.rb",
    "spec/model/shared_behaviors.rb",
    "spec/model/tag_spec.rb",
    "spec/spec_helper.rb",
    "spec/spec_ptj.rb",
    "tasks/db.rake",
    "tasks/irb.rake"
  ]
  s.homepage = %q{http://github.com/jgrunzweig/ptj}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Password analysis and collection database.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<dm-core>, [">= 0"])
      s.add_development_dependency(%q<dm-migrations>, [">= 0"])
      s.add_development_dependency(%q<dm-types>, [">= 0"])
      s.add_development_dependency(%q<dm-transactions>, [">= 0"])
      s.add_development_dependency(%q<dm-aggregates>, [">= 0"])
      s.add_development_dependency(%q<dm-validations>, [">= 0"])
      s.add_development_dependency(%q<dm-serializer>, [">= 0"])
      s.add_development_dependency(%q<dm-timestamps>, [">= 0"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_development_dependency(%q<dm-postgres-adapter>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<dm-core>, [">= 0"])
      s.add_dependency(%q<dm-migrations>, [">= 0"])
      s.add_dependency(%q<dm-types>, [">= 0"])
      s.add_dependency(%q<dm-transactions>, [">= 0"])
      s.add_dependency(%q<dm-aggregates>, [">= 0"])
      s.add_dependency(%q<dm-validations>, [">= 0"])
      s.add_dependency(%q<dm-serializer>, [">= 0"])
      s.add_dependency(%q<dm-timestamps>, [">= 0"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_dependency(%q<dm-postgres-adapter>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<dm-core>, [">= 0"])
    s.add_dependency(%q<dm-migrations>, [">= 0"])
    s.add_dependency(%q<dm-types>, [">= 0"])
    s.add_dependency(%q<dm-transactions>, [">= 0"])
    s.add_dependency(%q<dm-aggregates>, [">= 0"])
    s.add_dependency(%q<dm-validations>, [">= 0"])
    s.add_dependency(%q<dm-serializer>, [">= 0"])
    s.add_dependency(%q<dm-timestamps>, [">= 0"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    s.add_dependency(%q<dm-postgres-adapter>, [">= 0"])
  end
end

